apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "debca995-bb10-489f-8b7e-7f69b3cf9bc2"
    keyvaultName: "RacAppHelmSecrets"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: JWT-SECRET
          objectType: secret
          objectAlias: JWT_SECRET
        - |
          objectName: POSTGRES-USER
          objectType: secret
          objectAlias: POSTGRES_USER
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret
          objectAlias: POSTGRES_PASSWORD
    tenantId: "a6cc90df-f580-49dc-903f-87af5a75338e"
  secretObjects:
    - secretName: global-jwt-secret
      type: Opaque
      data:
        - objectName: JWT_SECRET
          key: JWT_SECRET
    - secretName: postgres-credentials
      type: Opaque
      data:
        - objectName: POSTGRES_USER
          key: POSTGRES_USER
        - objectName: POSTGRES_PASSWORD
          key: POSTGRES_PASSWORD
    - secretName: company-service-secrets
      type: Opaque
      data: []
    - secretName: partner-service-secrets
      type: Opaque
      data: []
    - secretName: user-service-secrets
      type: Opaque
      data: []
    - secretName: invoice-service-secrets
      type: Opaque
      data: []
