apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt
  namespace: rac-app
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/tags: ""
config:
  header_names:
    - authorization
  cookie_names:
    - jwt
plugin: jwt

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-api
  namespace: rac-app
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: cors-plugin
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 3000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: protected-api
  namespace: rac-app
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: cors-plugin,jwt
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 3000
          - path: /companies
            pathType: Prefix
            backend:
              service:
                name: company-service
                port:
                  number: 3000
          - path: /partners
            pathType: Prefix
            backend:
              service:
                name: partner-service
                port:
                  number: 3000
          - path: /invoices
            pathType: Prefix
            backend:
              service:
                name: invoice-service
                port:
                  number: 8000
          - path: /invoice-pdf
            pathType: Prefix
            backend:
              service:
                name: invoice-to-pdf-service
                port:
                  number: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: rac-app
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
